### ISSUE TITLE
October 2019 meetup

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#104]
@ScottBrooks Do you have a sense of how long your gRPC talk is?

**Comment by ScottBrooks** [comment]
Depending on questions I can probably go around 20-30 minutes.

**Comment by nathany** [comment]
Sounds good. I'm not sure if we'll plan something else, or just have a short meetup and some social time.

**Comment by nathany** [comment]
Who's the food sponsor this month?

@matthias-stone

**Comment by ScottBrooks** [comment]
Improbable can sponsor food.

Scott

**Comment by nathany** [comment]
Awesome. I think we will order food at 6:30 and have it after the talk. That way we can take a head count first.

**Comment by matthias-stone** [comment]
Thanks for the great talk @ScottBrooks, I learned a lot!

If you have the time and desire, it'd be great if you could make a PR to this repo with your slides and sample code.
