### ISSUE TITLE
January 2020 meetup

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#106]
Jan 27

**Comment by nathany** [comment]
> You know what a killer talk would be? Migrating to Go Modules.
> Do I need to? When do I need to? How do I? What are the gotchas?

via Slack

**Comment by bertoldia** [comment]
Ugh, I did this at my work. It was mostly smooth, but there were some
gotchas...

**Comment by matthias-stone** [comment]
I've also done this, but didn't get bit too hard (started with a few greenfield projects before the migration)
My biggest gotcha has been the fact that the docker repo defaults to an old version, instead of something current (aurgh)

**Comment by bertoldia** [comment]
My biggest and still relevant gotcha was with external tooling (protoc) and
the path of versioned dependencies.

**Comment by nathany** [comment]
2 weeks until the meetup. what should we do?

**Comment by nathany** [comment]
1 week

**Comment by nathany** [comment]
@matthias-stone offered to do a talk on profiling
https://edmontongo.org/2020-01/
