### ISSUE TITLE
February 2020 meetup

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#107]
Feb 24

**Comment by stellentus** [comment]
Here were some of the ideas suggested at the January meetup:
* When does go inline? (Or, "Ways go's compiler is dumber than you'd expect")
* Deploying. Amazon vs Google vs internal. Cheap vs easy options.
* Something along the lines of architecting complex applications (load balancing, etc.)
* Caddy
* Web sockets (Lewis suggested something specific related to this)
* Basic instrumentation with Prometheus (Lewis again)

**Comment by nathany** [comment]
Who wants to do a talk next week?

**Comment by nathany** [comment]
https://www.youtube.com/watch?v=0c-1KJwSMCw State of Go 2020: changes since Go 1.12

**Comment by stellentus** [comment]
I thought I might have time this month, but I've been too busy because I started a new job.

**Comment by nathany** [comment]
Congrats

**Comment by nathany** [comment]
We can just watch that video, eat some pizza, and hang out. How's that sound?

**Comment by bertoldia** [comment]
When monthly meetings start up again, maybe we can watch and talk about this  presentation. https://www.youtube.com/watch?v=c78U0MZ4b_c The suggestion therein seems heretic, but the presentation was compelling.
