### ISSUE TITLE
February 2021 meetup

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#112]
Feb 22, 2021

* Errors package (Go 1.13+) @ppreeper 
* Panic https://www.youtube.com/watch?v=c78U0MZ4b_c, recommended by @bertoldia , @matthias-stone to set up OBS for a watch party

**Comment by nathany** [comment]
2 weeks left to prepare. How is everyone doing? @ppreeper @matthias-stone

**Comment by ppreeper** [comment]
I have been thinking about it in between getting a HA PostgreSQL environment going. But I will still be ready.

**Comment by nathany** [comment]
@ppreeper @matthias-stone All ready?

**Comment by ppreeper** [comment]
getting there. I will be ready for monday, had a busy week but going
over my notes to make sure I have my head.Wrap(err) correct.

-----Original Message-----
