### ISSUE TITLE
April 2021

### ISSUE THREAD

**Issue by matthias-stone** [edmontongo/presentations#115]
April 26, 2021

I'm presenting on Google Cloud Functions, does anyone else have something specific they'd like to share?

**Comment by nathany** [comment]
Ready?

**Comment by matthias-stone** [comment]
Let's say I'm on track ;)

**Comment by stellentus** [comment]
> Let's say I'm on track ;)

Okay, sure. 

Matthias is on track.

**Comment by nathany** [comment]
Awesome possum

**Comment by nathany** [comment]
Thanks Matthias
