### ISSUE TITLE
Planning for January 2015

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#18]
What should we do? Anyone have a talk they want to do?

Maybe a postmortem on the Gopher Gala or something learned from the Go Workshop?

**Comment by ccollicutt** [comment]
I don't have any ideas but I like that you're asking for suggestions. :)

**Comment by nathany** [comment]
How about a talk on using Amazon S3 with Go?

**Comment by nathany** [comment]
Anyone else been doing something interesting with Go and would like to share their experience?
