### ISSUE TITLE
Hosting the Gopher Gala (Local HQ)

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#19]
http://gophergala.com/
Jan 23-25, 2015 
6pm Fri to 6pm Sun

I have contacted Gopher Gala about hosting a Local HQ in Edmonton. Startup Edmonton is providing the space.

This is the same weekend as our Introduction to Go workshop (#8). We would like to encourage workshop attendees to participate in the gala to put what they've learned to practice.

Seeing as Matthias and I are both mentors for the workshop, is anyone willing to help us host the Gala? It essentially means being at Startup Edmonton and ensuring people find teammates (there are other events going on at Startup Edmonton the same weekend).

**Comment by nathany** [comment]
Global Game Jam is at the same time. http://madjam.ca/ggj
Make a game in Go?

**Comment by nathany** [comment]
@ScottBrooks Are you planning to do the hackathon from Startup Edmonton? Want to help host?

**Comment by ScottBrooks** [comment]
I'm hoping to be there some of the time.  Depending on what hosting entails, I could help out.

**Comment by nathany** [comment]
@ScottBrooks just being there and welcoming people who are participating in the gala.
