### ISSUE TITLE
Planning for February 2015

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#20]
Anyone want to give a talk? Feb 23.

@ScottBrooks Want to talk about the code for Gift?

**Comment by ScottBrooks** [comment]
I could probably put something together. I had a wonderful bug I noticed
1.5 hours before the submission that would be interesting to talk about.


On Jan 26, 2015, at 10:24 PM, Nathan Youngman <notifications@github.com>
wrote:

Anyone want to give a talk?

@ScottBrooks <https://github.com/ScottBrooks> Want to talk about the code
for Gift?

—
Reply to this email directly or view it on GitHub
<https://github.com/edmontongo/presentations/issues/20>.

**Comment by nathany** [comment]
Thanks.
