### ISSUE TITLE
May 2015 Lightning Talks

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#23]
May 25, 2015

* Containerizing Go and Redis with Docker, Chris Olsen

**Comment by chrisolsen** [comment]
I currently have 2 short topics that we could pick from.
1. Using the standard library http package and why you don't need anything else. 
2. Hello world app with docker containers for the app and Redis (more real-world example to what Fletcher did a while back)

**Comment by nathany** [comment]
@chrisolsen Either of those would be great. I finally began figuring out Docker + Redis this week. Think you could pick one and plan a 10 minute talk?

**Comment by chrisolsen** [comment]
I think the docker based topic is a little more exciting, so for now that is the one I would go with.

**Comment by nathany** [comment]
Cool. Looking forward to it. :+1:

**Comment by nathany** [comment]
You may want to come a bit early just to ensure that everything works with the TV (Apple TV, ChromeCast or HDMI).

**Comment by chrisolsen** [comment]
Will do

**Comment by chrisolsen** [comment]
So this morning I tried just restarting boot2docker, which restarts the virtualbox instance, and everything is working again :)

**Comment by nathany** [comment]
Nice. :-)

@chrisolsen Do you have a link to your GitHub repo or slides?

**Comment by chrisolsen** [comment]
[Here is the the repo](https://github.com/chrisolsen/answer-to-life), but with the branches it is kind of a gong show. I will clean things up and write something up to make it easier to understand.

**Comment by nathany** [comment]
Sure. If you want to revise the repo or do up some slides for https://speakerdeck.com/, we can update the EdmontonGo website with links.
