### ISSUE TITLE
September 2015 talks

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#27]
September 28.

* gorename - how the sausage is made by Matthias Stone
* Embedding Go into C by Scott Brooks

**Comment by matthias-stone** [comment]
Proposed talk:
go rename - how the sausage is made

**Comment by nathany** [comment]
:+1: 

@scottbrooks You mentioned shared libraries in Go 1.5, or you were previously thinking of doing a talk on working with binary formats.

**Comment by ScottBrooks** [comment]
Yeah, I actually did a test last night after the meetup, and got some C code to link against a go shared library, and static library.  The round trip of Go calling the Go shared library via CGO doesn't seem to be supported.  I ran into a bunch of header issues in the code that cgo was generating.

I can do a talk on embedding go into C though.

**Comment by nathany** [comment]
Cool. I'm looking forward to learning more about C/Go interactions.

**Comment by nathany** [comment]
@ScottBrooks for September?

**Comment by ScottBrooks** [comment]
Yeah, I'll get something for ready for the September meet up.

Scott

On Aug 25, 2015, at 4:08 PM, Nathan Youngman <notifications@github.com>
wrote:

@ScottBrooks <https://github.com/ScottBrooks> for September?

—
Reply to this email directly or view it on GitHub
<https://github.com/edmontongo/presentations/issues/27#issuecomment-134756624>
.

**Comment by nathany** [comment]
Thanks @ScottBrooks. You may be interested in this proposal:
https://go-review.googlesource.com/#/c/14112/2/design/12416-cgo-pointers.md,unified

**Comment by nathany** [comment]
@ScottBrooks @matthias-stone Would you like to meet to do a practice run through your talks? A few days or a week before the meetup? 

It's a practice they do at the Python meetup that I've found helpful when I've done it.

**Comment by matthias-stone** [comment]
I'm available from the 23rd on, otherwise I am quite busy.

**Comment by nathany** [comment]
How are the talks going?

**Comment by matthias-stone** [comment]
I've decided to expand mine a little, and talk a little more generally about the tools that use parse. @ScottBrooks, are you free to meetup and practice tomorrow or Sunday? Or are you comfortable enough with what you have?

**Comment by ScottBrooks** [comment]
I've got a git repo for mine that has a commit for each of my learning steps on how to embed go into C, so I plan on going through it commit by commit to show the lessons learned.

My tentative title is "When the destination is boring, the journey is hopefully interesting."

**Comment by ScottBrooks** [comment]
When would work for you to get together?  After 7:00 pm either night works
for me.

Scott

On Sep 25, 2015, at 1:17 PM, Matthias Stone <notifications@github.com>
wrote:

I've decided to expand mine a little, and talk a little more generally
about the tools that use parse. @ScottBrooks
<https://github.com/ScottBrooks>, are you free to meetup and practice
tomorrow or Sunday? Or are you comfortable enough with what you have?

—
Reply to this email directly or view it on GitHub
<https://github.com/edmontongo/presentations/issues/27#issuecomment-143327868>
.

**Comment by matthias-stone** [comment]
I can't do tonight, so Sunday. What time and place, and are you okay meeting as late as 9? (Though I can make 7 work)

**Comment by ScottBrooks** [comment]
Yeah, 9:00 works for me. Where do we meet?

Scott

On Sep 26, 2015, at 1:36 PM, Matthias Stone <notifications@github.com>
wrote:

I can't do tonight, so Sunday. What time and place, and are you okay
meeting as late as 9? (Though I can make 7 work)

—
Reply to this email directly or view it on GitHub
<https://github.com/edmontongo/presentations/issues/27#issuecomment-143483896>
.

**Comment by matthias-stone** [comment]
Remedy Cafe on 109th?

**Comment by ScottBrooks** [comment]
Works for me. See you at 9:00.

On Sep 27, 2015, at 1:31 PM, Matthias Stone <notifications@github.com>
wrote:

Remedy Cafe on 109th?

—
Reply to this email directly or view it on GitHub
<https://github.com/edmontongo/presentations/issues/27#issuecomment-143589163>
.

**Comment by nathany** [comment]
I don't think I'm going to make it out. See you tomorrow guys.

**Comment by ScottBrooks** [comment]
I'm headed over there now, so I'll be there if you want to start earlier.

On Sep 27, 2015, at 1:31 PM, Matthias Stone <notifications@github.com>
wrote:

Remedy Cafe on 109th?

—
Reply to this email directly or view it on GitHub
<https://github.com/edmontongo/presentations/issues/27#issuecomment-143589163>
.

**Comment by nathany** [comment]
If you have slides, please consider adding a link here, and I'll link them from the website.

Can be after tonight, if you prefer.
