### ISSUE TITLE
October 2015 talks

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#30]
October 26th.

With the Mega Meetup the previous week, we may attract some new folks. An introductory talk would be good.

It's also the same day as WordPress meetup. Go for PHPers? Heh. :grinning: 
Thing is, a lot of those meetup goers are new to WordPress and PHP/HTML/CSS too.

**Comment by nathany** [comment]
@lroza mentioned doing a talk on cgo (using C from Go)

**Comment by stayorgo** [comment]
how do you folks do your talks? Projector, hook up laptop ?  Chalk board and felt (old school, haha). I would do a talk on parsing HTML and extracting data from the internet without using any regexes, but, I'm afraid I'm not an expert in Go and this talk would not be ready this time. I'm converting a lot of my existing source code over to Go, and when converting it it means not perfect Go until I become more of an expert.  Thanks for this interesting meetup in edmonton, didn't know about it until now. Great work. Do you folks prepare your talks with OpenOffice, Powerpoint, or something similar? Or do you just use the command line and Go to prepare your talks to stdout (kidding).

**Comment by matthias-stone** [comment]
We're open to pretty much any format, you can check out this git repository to see a selection of past talks.

Formats have included:
* Slides/Presentation
* Live coding session
* The [go present tool](https://godoc.org/golang.org/x/tools/present)
* Leading a group discussion
* Hacking sessions

**Comment by nathany** [comment]
I guess I should consider doing a talk. Probably something on collections.

There are some good talks from GolangUK that we could watch.
https://www.youtube.com/channel/UC9ZNrGdT2aAdrNbX78lbNlQ/videos

**Comment by ScottBrooks** [comment]
How about a dramatic reading from chapter 1.

Scott

On Oct 15, 2015, at 9:31 PM, Nathan Youngman <notifications@github.com>
wrote:

I guess I should consider doing a talk. Probably something on collections.

There are some good talks from GolangUK that we could watch.
https://www.youtube.com/channel/UC9ZNrGdT2aAdrNbX78lbNlQ/videos

—
Reply to this email directly or view it on GitHub
<https://github.com/edmontongo/presentations/issues/30#issuecomment-148589480>
.

**Comment by nathany** [comment]
* Matthias lightning talk on the go present tool
* I've been debating what to talk about, but I may do something on functional programming based on the examples in Chapter 3 of my book (which isn't quite finished yet).
* Watch Stupid Gopher Tricks by Andrew Gerrand with disccusion to follow

**Comment by nathany** [comment]
https://edmontongo.org/2015-10/
