### ISSUE TITLE
November 2015 talks

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#31]
Go's open source birthday is in November. Six years old.

**Comment by nathany** [comment]
James really wants to do a talk. :smile:

**Comment by grrtrr** [comment]
I will be looking into implementations of work queues / reliable messaging systems in Go and could present on that.

**Comment by nathany** [comment]
sounds like a good topic. I'd be interested in listening to your presentation :-)

**Comment by nathany** [comment]
Only one week until the meetup.

@grrtrr Can I update the website with your talk title?

**Comment by grrtrr** [comment]
Yes, title should be along the lines of _"Messaging and job queue design patterns in Go"_.

**Comment by chrisolsen** [comment]
@grrtrr I'm looking forward to this one :+1:
