### ISSUE TITLE
January 2016 talks

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#32]
January 25. Year 3. Meetup 24.

What should we talk about?

**Comment by nathany** [comment]
I could plan for a talk on concurrency in January.

**Comment by nathany** [comment]
Go 1.6 should be due out February. What's new in 1.6? [no details yet](http://tip.golang.org/doc/go1.6)

**Comment by matthias-stone** [comment]
@stellentus is likely going to give a talk on code organization.

**Comment by nathany** [comment]
sweet!

**Comment by nathany** [comment]
We'll do a Gala recap. 

Not sure if @stellentus will have a talk ready. That could always be in February.

Maybe we can spend some time summarizing Go 1.6 based on the release notes and experiences. http://tip.golang.org/doc/go1.6

**Comment by stellentus** [comment]
I won't have a talk ready.
