### ISSUE TITLE
2016 Holidays

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#34]
February, we may have the WordPress meetup the same day due to Family Day the previous week.

March meetup falls on Easter Monday. Perhaps we can move it to the 21st (same days as WordPress meetup).
May meetup falls on Victoria Day (May long weekend). Perhaps we can move it to the 30th.
December meetup falls on Boxing Day. We'll probably cancel this one again.

http://www.statutoryholidays.com/alberta.php

**Comment by nathany** [comment]
@tammalee for your info as well.

**Comment by tammalee** [comment]
Thanks for the heads up @nathany! Maybe we could do some sort of cross-promotion on those evenings we both have meetups? Are there areas where Go and WordPress intersect? I can do some research on my end.

**Comment by nathany** [comment]
Hm. Good idea, but I think are audiences are pretty different.
