### ISSUE TITLE
Gopher Gala  2016

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#36]
Chat in Slack. Once we have teams and projects figured out, we should add them here, and perhaps update the web page.

https://edmontongo.org/2016-gala/

**Comment by nathany** [comment]
Nathan:

* I'd like to create an open source library similar to Gobot and EMBD, but specifically for Raspberry Pi HATs, starting with the SenseHAT (temperature, pressure, screen, joystick, etc.).
* These HATs usually have Python libraries but I'd like a library for Go.
* A Hugo website for a blog, documentation, examples, maybe a video.

I only have one SenseHAT, and it may be too late to get order another one before the Gala. :-(
Could use help with design, testing, writing examples and docs. So far I haven't done any research into what's required to make this happen or existing libraries that could work.

**Comment by matthias-stone** [comment]
My team of 3 will be writing gobotgo. A server for hosting and organizing bots that play go, written in go.

**Comment by ScottBrooks** [comment]
I'll be working on gopher-typer, a terminal game about typing.

**Comment by iamkether** [comment]
My team of 3 is going to be working on a web-sockets enabled "gopher tanks" game... feels like a basic 2D tile-based shooter or something, but we're not quite sure of the implemntation details yet.

**Comment by nathany** [comment]
https://github.com/gophergala2016/bobblehat
https://github.com/gophergala2016/gopher_typer

**Comment by nathany** [comment]
List all our entries at https://edmontongo.org/2016-01/
