### ISSUE TITLE
February 2016 release party for Go 1.6

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#37]
Let's start planning so we can announce the talks early on.

**Comment by nathany** [comment]
I could do Go *Pointers 101.

**Comment by nathany** [comment]
Participating in the Go 1.6 release party with talks about what's new in Go 1.6.

https://github.com/golang/go/wiki/Go-1.6-release-party

(not sure the exact release date, but we'll meet at our regularly scheduled Feb 22)

**Comment by nathany** [comment]
Here's a slide deck of new things in Go.
https://talks.golang.org/2016/state-of-go.slide#1

**Comment by grrtrr** [comment]
The HTTP/2 changes sound great, it would be good to have some information.

I could do a short one on the new support for vendoring packages, and where this may make sense?

**Comment by nathany** [comment]
@grrtrr A short talk on using third-party packages would be great.

**Comment by nathany** [comment]
To make my talk more than one slide, I'll have to share my experiences using HTTP/2 and why it's important.

**Comment by nathany** [comment]
Who wants to do a talk on redefining blocks in templates? 

/cc @matthias-stone :wink:

**Comment by nathany** [comment]
Or if someone wants to talk about HTTP/2, I can do templates instead. I don't have a lot of experience with them, but how hard could it be?

**Comment by nathany** [comment]
Another new thing in Go 1.6 is the C/Go interop having rules about pointers that are checked at runtime.

**Comment by nathany** [comment]
@mckayb24 Is going to cover the new template features.
@matthias-stone is covering the new C/Go interop rules
@grrtrr is planning to talk about the vendor experiment stuff.

I may share some experiences using HTTP/2, even though the API hasn't changed. @abramhindle gave a great HTTP/2 talk at the January JavaScript meetup. I would rather build on that than replicate it.

For this month we want to keep the talks fairly short (20 minutes max). We're primarily covering what's new, though it makes sense to give a few minutes introducing the topic to newcomers.

@mckayb24 The new template features remind me of template inheritance in Django. That may be an interesting angle to look into. Maybe we can get some Python users out to the meetup to see how it compares. https://docs.djangoproject.com/en/1.9/ref/templates/language/

@matthias-stone here's one example of running into the interop rules: https://github.com/rjeczalik/notify/issues/90

@grrtrr the focus is on vendor experiment with tools like godep and gvt. but maybe take a look at this article too https://medium.com/@sdboyer/so-you-want-to-write-a-package-manager-4ae9c17d9527#.m7lip29jo or the alternative to the go tool, https://getgb.io/

**Comment by nathany** [comment]
@grrtrr https://github.com/kardianos/govendor may also be worth checking out.

**Comment by nathany** [comment]
Turns out HTTP/2 doesn't just work anymore. Have to opt-in in Go 1.6 final. 

Yay! I have something to talk about.

**Comment by grrtrr** [comment]
Ack. Did not like the article you mentioned (too many swear words), but will certainly look at the other sources.

**Comment by nathany** [comment]
hah. sorry.

**Comment by nathany** [comment]
Updates to the website are over here: https://github.com/edmontongo/edmontongo.org/pull/10

**Comment by nathany** [comment]
Sydney slides with some other new goodies in Go 1.6 http://go-talks.appspot.com/github.com/davecheney/gosyd/go1.6.slide#1

**Comment by nathany** [comment]
HTTP/2 push_promise to come in Go 1.7.

Another slide deck: https://docs.google.com/presentation/d/1JsCKdK_AvDdn8EkummMNvpo7ntqteWQfynq9hFTCkhQ/view#slide=id.g39982b998820aa42_366

**Comment by nathany** [comment]
Thanks everyone!

**Comment by nathany** [comment]
@grrtrr Do you have a link to your slides that can be added to the website?
