### ISSUE TITLE
March 2016 talks

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#38]
~~I could do Go *Pointers 101.~~

**Comment by nathany** [comment]
Maybe @stellentus will have a talk ready?

**Comment by stellentus** [comment]
I'm sure of what I'd talk about. I was considering Project Organization in Go, but I don't think I have enough content (and experience) to do a whole talk on that. Maybe it could be a discussion.
I'd prefer present about something I'm more experienced with, but I can't think of anything that would be interesting.

**Comment by nathany** [comment]
A talk doesn't need to be long. It can be 5 minutes or 10. 

I'd be interested in your experiences organizing projects. It doesn't need to be the perfect talk. It's about learning from each other, because we're all different.

**Comment by chrisolsen** [comment]
I would be willing to do one on creating web apps.

**Comment by nathany** [comment]
@chrisolsen :+1: sounds good. shall I mark you down for March 21?

**Comment by chrisolsen** [comment]
March 21 works for me

**Comment by nathany** [comment]
Thanks @chrisolsen. Enjoyed your talk and I learned a lot too.
