### ISSUE TITLE
May 2016 talks

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#43]
May 30, 2016

**Comment by nathany** [comment]
I haven't done a talk since January, so I probably should in May. Right now I don't have a topic though

**Comment by chrisolsen** [comment]
I was thinking about doing a talk on appengine.

**Comment by nathany** [comment]
That would be great @chrisolsen. Have you played with the Flexible (Managed VM) stuff at all?

**Comment by chrisolsen** [comment]
I haven't. I just found out about them recently when I saw them listed in the docs.

**Comment by matthias-stone** [comment]
I'd be interested in hearing this Chris, is it something you're willing to commit to at this point (ie, can I post it to the website?)

**Comment by chrisolsen** [comment]
Yes, you can add it to the schedule. I didn't realize I was so vague in my initial post.

**Comment by grrtrr** [comment]
If that would fit your planning, I have something on [stateful messaging](http://nanomsg.org/) (aka _"Scalability Protocols"_) and [go-mangos](https://github.com/go-mangos/mangos).

**Comment by matthias-stone** [comment]
@grrtrr, how long are you thinking your presentation would be?
@chrisolsen, how long do you think you will be prepared to talk for?

I have an alternative activity planned, I just want to know if it will fit.

**Comment by grrtrr** [comment]
@matthias-stone  - without demo circa 15 minutes, with demo about 25 minutes. It does not have to be this month.

**Comment by chrisolsen** [comment]
@matthias-stone I would estimate mine will be about 15-20min excluding any questions after, but I still have to put the presentation together so I might be a little off.

**Comment by matthias-stone** [comment]
Thanks guys. I'll add @grrtrr to the schedule, I think we should have time for everything (and if we don't have activity time, I'm super okay with that).

**Comment by nathany** [comment]
Thanks for your talks @chrisolsen and @grrtrr.

Please upload your slides to this repo or provide me a link to them. We'll link them up from the website.
