### ISSUE TITLE
June 2016 talks

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#44]
Go 1.7 beta and code sharing exercise?

https://tip.golang.org/doc/go1.7

**Comment by nathany** [comment]
Should we have people submit code to look at during the month and we'll pick a few?

**Comment by chrisolsen** [comment]
That is a good idea. If it is made known what will be looked at prior to the meet up it would allow everyone to checkout the code and have any questions ready for the meet up.

**Comment by chrisolsen** [comment]
What do you guys think about if we had *lightening demos* of small, recently completed Go apps? The <10min talk would cover how Go was used and any problems that were solved. We could allot space at either the start or end of the presentation for a few demos every month, but if there are no demos scheduled we just proceed as usual.

This might be motivation enough for people to work on small side projects done on personal time or the hack weekends.

**Comment by grrtrr** [comment]
Code sharing exercise, in whichever form, is a great idea.
I am looking on using unikernels with Go - might this be of interest (if anything, it would be short)?

**Comment by nathany** [comment]
@grrtrr https://github.com/unigornel/unigornel?

**Comment by grrtrr** [comment]
[unigornel](https://www.unigornel.org/) is very interesting. I was thinking of [EMC's unk]( https://github.com/emc-advanced-dev/unik) which compiles Go into a [rumpkernel](http://rumpkernel.org/) or Java into [OSv](http://osv.io/).

**Comment by nathany** [comment]
@grrtrr I heard of unik on gotime.fm as well. did you get to talk about it in your group? 

if not, then perhaps next time.
