### ISSUE TITLE
July 2016 talks

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#47]
July 25, 2016 - the 30th Edmonton Go meetup

**Comment by nathany** [comment]
Perhaps I'll talk about GopherCon. Last year I didn't prepare well enough to do that, so it wasn't great.

Anyone else interested in presenting?

**Comment by grrtrr** [comment]
I can't agree, found that both the visuals and the story telling of last year's GopherCon were outstanding.

Am still interested in go+unikernels, but am not really sure that is of general interest. Maybe they are 'varsity kernels'.

**Comment by nathany** [comment]
@grrtrr there was a unikernels talk at GopherCon :-) I don't imagine the videos will be out until August though.

**Comment by grrtrr** [comment]
Did you mean [AtmanOS](https://github.com/gophercon/2016-talks/tree/master/BernerdSchaefer-GoWithoutTheOperatingSystem)? Had not heard of it before, sounds interesting.

Am amazed at the number of projects around this topic.

**Comment by nathany** [comment]
Yup.
