### ISSUE TITLE
September 2016 talks

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#49]
September 26 -- anyone interested in presenting?

**Comment by nathany** [comment]
NOTE: parking meters may not be free anymore -- when there is an event

**Comment by nathany** [comment]
@grantdhunter on Rust

**Comment by nathany** [comment]
@fnichol on Rust

**Comment by chrisolsen** [comment]
Sounds like I missed out, but with the oilers' game last night there was zero parking.

**Comment by nathany** [comment]
Yah, people had to take transit or park fairly far away. It looks like there isn't an event for the meetup next month, so parking should be fine.
