### ISSUE TITLE
October 2016 talks

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#50]
October 24th

Moved @boersn's talk to next month. #51

**Comment by nathany** [comment]
@grrtrr on https://godoc.org/golang.org/x/sync/errgroup

**Comment by grrtrr** [comment]
Actually (pun not intended), I wanted to add some [context](https://blog.golang.org/context) to it. In the sense of [design patterns](http://blog.ralch.com/tutorial/), perhaps e.g. "barrier" pattern, with examples.

**Comment by nathany** [comment]
okay. Please let me know the title for you talk so I can update the website. Thanks Gerrit!

**Comment by grrtrr** [comment]
Title is _"Barrier Pattern in Go (with Context)"_, aiming for about 20..25 minutes if that is not too long.

**Comment by nathany** [comment]
possibly related: https://www.oreilly.com/learning/run-strikingly-fast-parallel-file-searches-in-go-with-sync-errgroup

**Comment by chrisolsen** [comment]
Turns out a small helper library that I wrote is unintentionally similar to errgroup. It's hard not to like Go's channels.
https://github.com/chrisolsen/async

**Comment by grrtrr** [comment]
@chrisolsen - I was in the same situation, had almost written something, and then found this.

_Here is a short plan of the talk_: 
The term [Barrier](https://en.wikipedia.org/wiki/Barrier_%28computer_science%29) is loosely used to mean "waiting for a group of goroutines to finish". This can be generally accomplished using [`sync.WaitGroup`](https://golang.org/pkg/sync/#WaitGroup). However, that does not cover _error handling_ -  what to do if one or more worker goroutines fail. The [`sync/x/errgroup`](https://godoc.org/golang.org/x/sync/errgroup) allows to cancel all workers if the first error is encountered. This works really well when combining `errgroup` with a cancellation [`Context`](https://golang.org/pkg/context/). Examples will be provided to show how these components usefully work together.

**Comment by grrtrr** [comment]
2+1 suggestions of _GolangUK 2016 videos_ that might be interesting to watch some future time:
* [Dave Cheney - _SOLID Go Design_](https://www.youtube.com/watch?v=zzAdEt3xZ1M&list=PLDWZ5uzn69eyh791ZTkEA9OaTxVpGY8_g&index=28) - _Craftsmanship is not defined by tools, but their use._
* [Mat Ryer - _Idiomatic Go Tricks_](https://www.youtube.com/watch?v=yeetIgNeIkc&index=21&list=PLDWZ5uzn69eyh791ZTkEA9OaTxVpGY8_g) - _Lots of good advice._
* [Ernesto Jimenez - _Inception: Go programs that generate Go code_ ](https://www.youtube.com/watch?v=Zl50bk6VRQE&list=PLDWZ5uzn69eyh791ZTkEA9OaTxVpGY8_g&index=9) - _Full of good stuff and inspiring ideas_.

**Comment by nathany** [comment]
@grrtrr how are the preparations for your talk coming along?

I haven't prepared a talk or even picked a topic, so we'll probably watch one of these GolangUK talks.

**Comment by grrtrr** [comment]
I am wrapping up things today and tomorrow, with examples on the slides; perhaps 1 or 2 as standalone. If there is anything else you think may be interesting to look at "in this context", please let me know.

**Comment by nathany** [comment]
@grrtrr Thanks for your talk. Really enjoyed it. Do you have a link to your slides? Or can you add them to this repo in a pull request?

**Comment by grrtrr** [comment]
Hm, I sent in a pull request last night - could you please check it over?

**Comment by nathany** [comment]
Looks good. Thanks.
