### ISSUE TITLE
November 2016 talks

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#51]
November 28th

@boersn ~~From Processes to Go Routines: A Look at the Evolution~~ ~~Coding for Concurrency - A Brief Exploration of Processes, Threads, and Go~~ Coding for Concurrency: Processes, Threads, and Goroutines

~~@nathany (yet untitled talk on channels, select, and the sync package?)~~

**Comment by nathany** [comment]
@boersn can I add your November 28th talk to the web site?

**Comment by nathany** [comment]
@torbiak is interested in doing a [review](https://www.amazon.com/gp/customer-reviews/R1UN5ENPRC3ROH/ref=cm_cr_getr_d_rvw_ttl?ie=UTF8&ASIN=0134190440) of The Go Programming Language (book). Presenting some of the exercises, etc.

**Comment by lukaszroz** [comment]
Jordan talk https://github.com/torbiak/goplreview

**Comment by nathany** [comment]
Thanks, got it: https://edmontongo.org/2016-11/
