### ISSUE TITLE
January 2017

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#53]
What should we do? @mckayb24

**Comment by adamwg** [comment]
I've unfortunately had to miss the last couple meetings but have been thinking about putting together a presentation on Protocol Buffers and gRPC in Go. If there's interest I could definitely get it together for January.

**Comment by nathany** [comment]
@adamwg That'd be awesome. We haven't had any talks on protobufs yet.

@mckayb24 is thinking of doing a talk on interfaces in practice.

**Comment by adamwg** [comment]
@nathany Sounds good. I will put something together in time for the January meetup, but happy to push it to February as well if @mckayb24 has January locked up :-).

**Comment by nathany** [comment]
@adamwg Two talks is about right.

If you two have titles for your talks, I'll go ahead and update the website and start promoting the January meetup.

**Comment by nathany** [comment]
Hi @adamwg and @mckayb24. How are your preparations going for January 23rd?

**Comment by mckayb24** [comment]
I've been thinking about it but haven't actually planned anything yet. It should be ready for the 23rd though.

Get Outlook for Android<https://aka.ms/ghei36>



On Wed, Jan 4, 2017 at 12:34 PM -0700, "Nathan Youngman" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @adamwg<https://github.com/adamwg> and @mckayb24<https://github.com/mckayb24>. How are your preparations going for January 23rd?

**Comment by adamwg** [comment]
I have started making some slides. Will definitely be ready for Jan 23.

**Comment by nathany** [comment]
@adamwg @mckayb24 Thanks for the excellent talks.

Please provide links to your slides or send a pull request into this repository.

**Comment by nathany** [comment]
20 people out today. Nice!

18 guys and 2 gals. 

Gotta work on that ratio, maybe help start a women who Go chapter in Edmonton.

**Comment by mckayb24** [comment]
Hey Nathan, I tried to add my talk but I don't have push access. Can you help me out?

**Comment by nathany** [comment]
@mckayb24 It looks like you hadn't accepted the invitation. I cancelled it and sent a new one, which you should receive via email. Please try again after accepting it. Thanks.
