### ISSUE TITLE
February 2017 meetup talks

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#54]
Our regular meetup is Feb 27, 2017

We should probably do something for Go 1.8
https://github.com/golang/go/wiki/Go-1.8-Release-Party
https://talks.godoc.org/github.com/davecheney/go-1.8-release-party/presentation.slide#1
https://github.com/davecheney/go-1.8-release-party

**Comment by matthias-stone** [comment]
I'd want to show some of the new stuff with context (db!), but Gerrit talked about Context a bit in October, I'm not sure if there's lots of overlap (or interest).

Maybe just a quick (5-20 minute) overview?

**Comment by nathany** [comment]
Go 1.8 lightning talks?!

**Comment by nathany** [comment]
also could talk about the plans for Go 1.9, or related topics like the new dep tool

Russ Cox's Go Resolutions for 2017 https://research.swtch.com/go2017
Go 1.9 planning https://groups.google.com/forum/#!topic/golang-dev/Dn-pfWETUrM

**Comment by lukaszroz** [comment]
I will do lightning talk about new HTTP Server Graceful Shutdown

**Comment by waltonr8** [comment]
I will do a lightning talk on the new GOPATH default.

**Comment by nathany** [comment]
Thanks @lukaszroz. There have been a number of graceful shutdown libraries in the past that this can hopefully replace the need for. I've personally used [facebookgo/httpdown](https://godoc.org/github.com/facebookgo/httpdown) and [braintree/manners](https://github.com/braintree/manners).

Thanks @waltonr8. In addition to the [beta docs](https://beta.golang.org/doc/code.html), [and more docs](https://beta.golang.org/cmd/go/#hdr-GOPATH_environment_variable), you can refer to the issues that lead to this change if you want. The [initial proposal](https://github.com/golang/go/issues/12488), a [simplified proposal](https://github.com/golang/go/issues/17262), and [discussion of where this could go in the future](https://github.com/golang/go/issues/17271). These [slides](https://talks.godoc.org/github.com/davecheney/go-1.8-release-party/presentation.slide#12) look like they aren't done quite yet.

**Comment by grantdhunter** [comment]
I will do a lightning talk on Plugins.

**Comment by nathany** [comment]
@matthias-stone This may be useful: [What is new in database/sql?](https://docs.google.com/document/d/1F778e7ZSNiSmbju3jsEWzShcb8lIO4kDyfKDNm4PNd8/edit?usp=sharing) for your DB context talk. Some of the new database features are already in the pq driver, see [this issue](https://github.com/lib/pq/issues/531).

**Comment by nathany** [comment]
I'd like to end by mentioning some of the proposals that may land in Go 1.9 and the new `dep` tool.

**Comment by matthias-stone** [comment]
Is any body interested in discussing any of the other new database features?

**Comment by nathany** [comment]
Still a bunch of new stuff to talk about if anyone else wants to sign up: https://beta.golang.org/doc/go1.8

If I can help anyone with resources or going over your presentation, please reach out. My email is gopher@nathany.com.

**Comment by nathany** [comment]
@grantdhunter check out this repo https://github.com/campoy/golang-plugins

**Comment by nathany** [comment]
State of Go
https://www.youtube.com/watch?v=tY4UKkgb5IY
https://talks.golang.org/2017/state-of-go.slide#1

**Comment by nathany** [comment]
Another "what's new" slide deck
http://www.slideshare.net/huazhihao1/what-is-new-in-go-18-72210978

**Comment by nathany** [comment]
@grantdhunter another plugins demo https://github.com/kris-nova/go-plugin-demo

**Comment by nathany** [comment]
Is everybody ready for tomorrow?

**Comment by nathany** [comment]
@mckayb24 Are you preparing a lightning talk too?

**Comment by grantdhunter** [comment]
Yes I am ready

**Comment by nathany** [comment]
Looking forward to learning about plugins. Thanks @grantdhunter.

**Comment by grantdhunter** [comment]
I just got hit by a cold, I wont be able to make it tonight. Here is what I was going to present [https://github.com/grantdhunter/go_plugin_talk](https://github.com/grantdhunter/go_plugin_talk).

Feel free to present it and review the code sample with everyone.

**Comment by stellentus** [comment]
I'll do sort.Slice or whatever it's called

**Comment by nathany** [comment]
Everyone please upload your slides to the presentations repo under the "2017-02" folder or provide a link.

**Comment by stellentus** [comment]
@nathany my talk didn't have any slides. Should I just create a "slice sort" folder and put my 4 code files in there? I guess it might still be useful even without explanation?

**Comment by nathany** [comment]
@stellentus yes please

**Comment by nathany** [comment]
@stellentus If you add your code to https://github.com/edmontongo/presentations/tree/master/2017-02, I'll link it up from the web site. Thanks!

**Comment by stellentus** [comment]
@nathany I (finally) have a commit to add this, but I don't think I have permissions to push it.

**Comment by nathany** [comment]
@stellentus Sorry about that. I've added permissions for you.

**Comment by stellentus** [comment]
I pushed it.

**Comment by nathany** [comment]
thanks
