### ISSUE TITLE
March 2017 meetup talks

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#57]
March 27, 2017 Meetup #37

Concurrency focus:

* Concurrency in Go: goroutines, channels, select, one-way channels, closing channels, nil channels - @nathany
* the atomic package - @lukaszroz 

Other topics:
* intro to concurrency (as a concept, history)
* concurrency patterns
* mutexes and when to use them
* WaitGroup (sync package)
* Pool, etc. (sync package)
* x/sync/errgroup
* race detector, built-in and -race

**Comment by lukaszroz** [comment]
Is this going to be in a lightning talk format? If so, I can do some short presentation about the atomic package.

**Comment by nathany** [comment]
Could do lightning format. The intro might be more like 15 minutes though, not sure.

**Comment by grrtrr** [comment]
I would be happy to do a walk-through of basic concurrency patterns - there is a growing list of idioms (generator, pipeline, cancellation, ...) - all using channels. No mutexes, please :-)

**Comment by nathany** [comment]
Sounds good @grrtrr.

**Comment by nathany** [comment]
I'm thinking of playing this video: https://www.youtube.com/watch?v=SmoM1InWXr0

**Comment by grrtrr** [comment]
It is referred to in my slides as part of the Resources.

**Comment by nathany** [comment]
My talk will just cover goroutines, the very basics. (Sorry, I haven't prepared more 😢 🐼 )

Leaving channels to @grrtrr (and possibly John's video).

**Comment by nathany** [comment]
@grrtrr @matthias-stone @lukaszroz Slides please. Mine are here #60.

Thanks everyone.

**Comment by grrtrr** [comment]
@nathany - thanks. Mine are in #62

**Comment by lukaszroz** [comment]
See #63
