### ISSUE TITLE
April 2017 meetup

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#61]
April 24th. What shall we do?

**Comment by nathany** [comment]
How about a Q&A panel?

We would need a moderator with some prepared questions in case there is a lull in audience questions.

And then a few volunteers to take questions.

We could have a theme or just go AMA style.

**Comment by matthias-stone** [comment]
I'd be cool with a Q&A panel, ideally paired with a substantive talk. How should we go about picking panel members? Nominations/seconds? @nathany and I pick a representative cross section of the community?

Alternatively, we could do something small group oriented (like code reading), as that requires a small amount of organization, and has a high level of engagement (hard for people to be left out of a group of 3 or 4).

**Comment by matthias-stone** [comment]
Okay. Going with the idea of "lightning talks on golang.org/x/..."

- 5-15 minutes, doesn't have to be too fancy.
- Pick a module in one of the below repos, and give a talk! It'll be fun, they say. You'll get paid, they say (we don't).
- Note that some of the links are... weird? like x/crypto.

https://godoc.org/golang.org/x/arch/
https://godoc.org/golang.org/x/benchmarks/
https://godoc.org/golang.org/x/blog/
https://godoc.org/golang.org/x/build/
https://godoc.org/golang.org/x/crypto/
https://godoc.org/golang.org/x/debug/
https://godoc.org/golang.org/x/exp/
https://godoc.org/golang.org/x/image/
https://godoc.org/golang.org/x/mobile/
https://godoc.org/golang.org/x/net/
https://godoc.org/golang.org/x/oauth2/
https://godoc.org/golang.org/x/perf/
https://godoc.org/golang.org/x/playground/
https://godoc.org/golang.org/x/review/
https://godoc.org/golang.org/x/sync/
https://godoc.org/golang.org/x/sys/
https://godoc.org/golang.org/x/talks/
https://godoc.org/golang.org/x/text/
https://godoc.org/golang.org/x/time/
https://godoc.org/golang.org/x/tools/

Full list: https://godoc.org/-/subrepo

Any takers? I'm down for golang.org/x/crypt/ssh

**Comment by nathany** [comment]
Cool. 

Yah, lets save the panel discussion thing for when we have more time to plan it.

**Comment by nathany** [comment]
We haven't seen enough interest in the golang.org/x theme, so we may end up doing something different. Maybe talks without a theme, maybe some other activity... 

Suggestions welcome.

**Comment by nathany** [comment]
@grantdhunter Have you been doing any Go lately? Have anything to share for Monday?

**Comment by grrtrr** [comment]
I am interested in discussing Reactive Programming in Go.                      
                                                                               
There is an upcoming [book](https://www.packtpub.com/application-development/go-reactive-programming) on [this](https://github.com/ReactiveX/RxGo) in September. The C# [reactive extensions](http://reactivex.io/) have really been taking off.       
                                                                               
There are things possible in Akka and Erlang that do not seemstraightforward in Go. Solving these would open up programming techniques that are proving useful in other languages.                         
                                                                               
Would that be of use?

**Comment by grantdhunter** [comment]
@nathany unfortunately I have not. I was going to take a look at one of the x modules if you still want a short talk on one of those.

**Comment by nathany** [comment]
@grrtrr @grantdhunter That would be good -- if you still have time to prepare something -- please let me know.

**Comment by grrtrr** [comment]
@nathany - yes will do.

**Comment by grantdhunter** [comment]
@nathany today got away from me. I wasn't able to dig deep into any of the x modules. I looked over the time one, so if you don't have anything I can do an improv thing on that.

**Comment by nathany** [comment]
@grrtrr thanks!

@grantdhunter Up to you. I plan to do a talk as well, so we should be okay either way.

**Comment by grantdhunter** [comment]
@nathany I won't make it too the meetup, I got food poisoning or something :(

**Comment by nathany** [comment]
:-( ugh. Hope you feel better soon

**Comment by nathany** [comment]
@grrtrr Hope you don't mind if I do my talk first. I'll try not to be too long.

**Comment by grrtrr** [comment]
@nathany - take as much time you like, mine can be as short as need be.

**Comment by nathany** [comment]
Thanks for your talk @grrtrr, especially on last minute notice.

Please push your presentation to the repo so I can link up the slides.

**Comment by grrtrr** [comment]
Just did this in  093c2214a44aeae031e2d5ad7f6ad8d3aab78ccc
