### ISSUE TITLE
May 2017 meetup

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#64]
May 29th

* panel discussion? #61 
* code gardening (bring your laptop)?
* talks

**Comment by nathany** [comment]
@lukaszroz willing to do a talk? got a topic?

**Comment by lukaszroz** [comment]
I am sorry, this month I won't be able to do it. I will try prepare something for June.

**Comment by nathany** [comment]
Okay. Thanks @lukaszroz

**Comment by nathany** [comment]
Less than 2 weeks until the meetup. What to do?

**Comment by nathany** [comment]
Anyone want to do a presentation or help plan a different activity?

**Comment by grrtrr** [comment]
@nathany - I could do _code generation_ (preferred) or _error handling_; very little time to prepare.

**Comment by nathany** [comment]
@grrtrr A talk on code generation would be great. Thanks!
