### ISSUE TITLE
Contribution workshop

### ISSUE THREAD

**Issue by schollz** [edmontongo/presentations#72]
Would there be any interest for someone to lead a Go contribution workshop (e.g. like [this one at GopherCon](https://blog.golang.org/contributor-workshop))?

I'd be really interested in doing a hands-on workshop to learn how to use Gerrit for submitting changes to Go and getting help at identifying places where a novice can introduce useful changes to the standard library.

**Comment by nathany** [comment]
Hi Zack,

I think we will need support from the Go team. The GopherCon contributor workshop had people merging CLs into a test repository.

relevant issue: https://github.com/golang/cwg/issues/13

Maybe this is something we could plan for in the new year?
