### ISSUE TITLE
January 2018 Meetup

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#74]
Jan 22, 2018

Testing.

**Comment by nathany** [comment]
@boersn @matthias-stone Still thinking about testing as a topic for January?

**Comment by nathany** [comment]
I may prepare a talk on errors for January, as that's the topic for the next chapter for my book.

**Comment by adamwg** [comment]
Would you like a second talk for Monday? I could put together a short one about a pattern I like in Go - the "functional option pattern" (similar to [this talk/post](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis)).

**Comment by nathany** [comment]
Hey Adam. Absolutely. I imagine some of the audience will be new to the variadic syntax in Go, and the functional option pattern is a really nifty way to use it. I'm also curious what situations you've found it useful.

**Comment by adamwg** [comment]
Sounds good - I'll put something together.

**Comment by nathany** [comment]
My talk isn't going to be exhaustive, so there should still be time for a third short talk.

**Comment by nathany** [comment]
Any jobs, news, or articles to highlight at the next meetup?

Go 1.10 beta 2 for sure.

**Comment by nathany** [comment]
Rehearsed my talk. It is about 30 minutes.

**Comment by nathany** [comment]
thanks
