### ISSUE TITLE
April 2018 Meetup

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#75]
April 23rd

@tammalee may do a talk on Hugo

**Comment by nathany** [comment]
If we have a Hugo talk, I may add one on deploying Hugo sites to S3 with bep/s3deploy (or something like that)

**Comment by nathany** [comment]
@tammalee Are you still interested in doing a Hugo talk in April?

**Comment by tammalee** [comment]
Absolutely! :D
What is the usual length?

**Comment by nathany** [comment]
20 minutes should be good. We don't really have a usual length though.

**Comment by tammalee** [comment]
Can do!
I'm hoping to give the CMS version a try, too.

**Comment by nathany** [comment]
There's a CMS version of Hugo? 🤯

**Comment by tammalee** [comment]
Yes! It's called Forestry and it pulls commits from Github to make updates
to  content. So, not really a client-friendly solution but I can see where
it might be useful.

**Comment by nathany** [comment]
https://forestry.io/blog/new-pricing-organization-accounts/

**Comment by tammalee** [comment]
Thanks!

**Comment by nathany** [comment]
@tammalee Do you have a title for your talk that I can add to the website? (It can always be updated later)

**Comment by tammalee** [comment]
Sure! How about, Meet Hugo the Static Site Generator?

**Comment by tammalee** [comment]
Here you go!
https://docs.google.com/presentation/d/1urWJlVGRKRL6F9KLYSmmvfWawFGvG4uFMpwxj1KDJ5Y/edit?usp=sharing

You may want to download as a PDF for the site.

Cheers!
Tammy
