### ISSUE TITLE
February 2018 Meetup

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#77]
February 26th

~~Testing databases~~ with ~~@matthias-stone~~ and @Brett-A-T-Anderson.

**Comment by ppreeper** [comment]
Could I do a lightning talk on using git bisect and go test to find regression bugs?

**Comment by nathany** [comment]
@ppreeper thanks. that’d be great. I’ll add it to the website. What should I call it?

**Comment by ppreeper** [comment]
Automate Git Repository Bisection with Go Test

**Comment by nathany** [comment]
Change of plans. Database testing talk is postponed. We'll do some lightning talks, including @ppreeper's talk.

Other possible topics include: Go 1.10 (new features) and vgo

https://golang.org/doc/go1.10
https://research.swtch.com/vgo

**Comment by stellentus** [comment]
Go 1.10 mostly looks boring (compared to previous releases). There are a few points that are definitely worth a brief mention, but not much to demo. A demo of `strings.Builder` could be interesting. Perhaps also a demo of `go vet` if that hasn't been done recently, since `go test` runs it by default.
But I don't have time to volunteer for one, anyway.

**Comment by nathany** [comment]
Thanks for looking into it. Yah, the "big feature" seems to be caching, doesn't make for much of a demo.

**Comment by nathany** [comment]
@ppreeper You can do your lightning talk before the coding practice.

**Comment by nathany** [comment]
@ppreeper Also, can you please find me beforehand, as I unfortunately don’t recall what you look like. 😞

**Comment by ppreeper** [comment]
Sure i can do it before the coding practice.
Attaching LinkedIn profile
https://www.linkedin.com/in/ppreeper/
And profile photo
https://www.linkedin.com/start/view-full-profile?_ed=0_eIgVUPwW5k2OSaUvKNggwtEcRqGDTFUZBRVbL4HnJy_&amp;trk=public_profile_atf-profile-pic%26quot%3B

**Comment by nathany** [comment]
Thanks Peter. Now I remember. 😃 

@Brett-A-T-Anderson do you have a lightning talk for tomorrow?

**Comment by nathany** [comment]
@Brett-A-T-Anderson no worries

**Comment by nathany** [comment]
@ppreeper If you get a chance to open a pull request to this repository with your slides, I'll link 'em up from the website.

**Comment by ppreeper** [comment]
pull request sent with added presentation

**Comment by nathany** [comment]
Thanks!

https://talks.godoc.org/github.com/edmontongo/presentations/2018-02/automate_gitbisect/automate_bisection.slide#1
