### ISSUE TITLE
October 2018 Meetup

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#90]
Go for Web Developers Workshop Part II
October 22, 2018

**Comment by nathany** [comment]
Should we ask Startup Edmonton about moving our meetup to 6pm so we have a little more time? (6-8:30)

**Comment by nathany** [comment]
@chrisolsen the darksky package based on today's work is here: https://github.com/edmontongo/darksky

**Comment by nathany** [comment]
Unrelated: did you see https://blog.golang.org/appengine-go111

**Comment by chrisolsen** [comment]
I did :) This is the first time that I remember that they were ever in sync.
