### ISSUE TITLE
February 2019

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#96]
Feb 25

If people find January's talk (#95) comparing Node.js and Go useful, I may follow up with a comparison of Elixir and Go.

**Comment by chrisolsen** [comment]
@nathany Comparing Go and Elixir is what I came here to suggest 👍 I have always wondered how using Go's channels compared to OTP.

**Comment by nathany** [comment]
Is anyone else will to do a talk in February?

**Comment by bertoldia** [comment]
Has the February meetup been bumped by AMII? The usually have their meetups on the Tuesday before this meetup, but I see on their calendar that they have one scheduled for the same day at an overlapping time (and at the same place) as this meetup.

Whats the deal?

https://www.eventbrite.ca/e/amiis-ai-meetup-tickets-54417539325?aff=ebdssbdestsearch

**Comment by nathany** [comment]
@bertoldia The Go meetup must Go on! I imagine both will happen simultaneously. We'll likely be in the kitchen area for our meetup, since we're a bit smaller.

**Comment by nathany** [comment]
I don’t have anything prepare for tomorrow. Might end up cancelling it.

**Comment by nathany** [comment]
Cancelled.
